rm(list=ls())
read.csv("heart_failure_clinical_records_dataset.csv")
library(dplyr)
library(gtools)
library(ggplot2)
library(tidyr)
library(caret)
library(ROCR)
library(skimr)
library(cowplot)
library(tidyverse)
library(skimr)# skimming data frames
library(ggthemes)
library(InformationValue)
library(ISLR)
library(patchwork) 
library(corrplot)
library(rsample)    
library(DescTools)  
library(sjPlot)     
library(caret)      
library(mlr)        
library(rpart)      
library(rpart.plot)
library(ranger)     
library(lightgbm)
heart <- read.csv("heart_failure_clinical_records_dataset.csv")
skim(heart)
df <- heart %>%
  mutate(sex = factor(sex, levels = c(0,1), labels = c("Female", "Male")),
         anaemia = factor(anaemia, levels = c(0,1), labels = c("No Anaemia", "Anaemia")),
         diabetes = factor(diabetes, levels = c(0,1), labels = c("No Diabetes", "Diabetes")),
         high_blood_pressure = factor(high_blood_pressure, levels = c(0,1),labels = c("No HBP", "BP")),
         smoking = factor(smoking, levels = c(0,1),labels = c("No Smoke", "Smoke")),
         DEATH_EVENT = factor(DEATH_EVENT, levels = c(0,1),labels = c("ALIVE","DEAD")))
glimpse(df)
xtabs(~ DEATH_EVENT + age, data = df)
xtabs(~ DEATH_EVENT + sex, data = df)
xtabs(~ DEATH_EVENT + anaemia, data = df)
xtabs(~ DEATH_EVENT + diabetes, data = df)
xtabs(~ DEATH_EVENT + high_blood_pressure, data = df)
xtabs(~ DEATH_EVENT + smoking, data = df)
xtabs(~ DEATH_EVENT + serum_creatinine, data = df)
xtabs(~ DEATH_EVENT + serum_sodium, data = df)
xtabs(~ DEATH_EVENT + ejection_fraction, data = df)
xtabs(~ DEATH_EVENT + creatinine_phosphokinase, data = df)
xtabs(~ DEATH_EVENT + platelets, data = df)
xtabs(~ DEATH_EVENT + time, data = df)
xtabs(~ DEATH_EVENT + DEATH_EVENT, data = df)
set.seed(0)
df_split <- initial_split(df, split = 0.8, strata = DEATH_EVENT)
train <- training(df_split)
test <- testing(df_split)
head(train)
logistic1 <-glm(DEATH_EVENT ~ sex, family = binomial(logit), data = train)
tab_model(logistic1, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic1)
PseudoR2(logistic1)
logistic2 <-glm(DEATH_EVENT ~ anaemia, family = binomial(logit), data = train)
tab_model(logistic2, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic2)
PseudoR2(logistic2)
logistic3 <-glm(DEATH_EVENT ~ diabetes, family = binomial(logit), data = train)
tab_model(logistic3, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic3)
PseudoR2(logistic3)
logistic4 <-glm(DEATH_EVENT ~ high_blood_pressure, family = binomial(logit), data = train)
tab_model(logistic4, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic4)
PseudoR2(logistic4)
logistic5 <-glm(DEATH_EVENT ~ smoking, family = binomial(logit), data = train)
tab_model(logistic5, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic5)
PseudoR2(logistic5)
logistic6 <-glm(DEATH_EVENT ~ serum_creatinine, family = binomial(logit), data = train)
tab_model(logistic6, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic6)
PseudoR2(logistic6)
logistic7 <-glm(DEATH_EVENT ~ serum_sodium, family = binomial(logit), data = train)
tab_model(logistic7, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic7)
PseudoR2(logistic7)
logistic8 <-glm(DEATH_EVENT ~ ejection_fraction, family = binomial(logit), data = train)
tab_model(logistic8, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic8)
PseudoR2(logistic8)
logistic9 <-glm(DEATH_EVENT ~ creatinine_phosphokinase, family = binomial(logit), data = train)
tab_model(logistic9, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic9)
PseudoR2(logistic9)
logistic10 <-glm(DEATH_EVENT ~ platelets, family = binomial(logit), data = train)
tab_model(logistic10, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic10)
PseudoR2(logistic10)
logistic11 <-glm(DEATH_EVENT ~ time, family = binomial(logit), data = train)
tab_model(logistic11, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic11)
PseudoR2(logistic11)
logistic12 <-glm(DEATH_EVENT ~ DEATH_EVENT, family = binomial(logit), data = train)
tab_model(logistic12, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logistic12)
PseudoR2(logistic12)

logisticf <-glm(DEATH_EVENT ~ ., family = binomial(logit), data = train)
tab_model(logisticf, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
summary(logisticf)
logistic <- step(logisticf)
tab_model(logistic, show.r2 = FALSE, transform = NULL, digits = 3, digits.p = 4)
PseudoR2(logistic)

predicted <- predict(logistic, test, type = "response")
test$DEATH_EVENT <- ifelse(test$DEATH_EVENT == "Yes", 1, 0)
optimal <- optimalCutoff(test$DEATH_EVENT, predicted) 
confusionMatrix(test$DEATH_EVENT,predicted)
sensitivity(test$DEATH_EVENT,predicted)
specificity(test$DEATH_EVENT,predicted)
misClassError(test$DEATH_EVENT,predicted,threshold = optimal)

sens <- sensemakr(logisticf, treatment = "diabetesDiabetes",benchmark_covariates = "high_blood_pressureBP", kd = 1:3)
sens

precision(test$DEATH_EVENT,predicted)
recall(test$DEATH_EVENT,predicted)





